image: node:latest

deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - cd boilerplate
    - npm install -g firebase-tools
    - npm install
    - npm build
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN